package main

import (
	"flag"
	"fmt"
	"strings"
	"os"
	"cuelang.org/go/cue/cuecontext"
)

func main() {
	if err := run(); err != nil {
		fmt.Println(err)
	}
}

func loadFromCue(configpath, schemapath string, v interface{}) error {
	// Load in configuration file
	configBytes, err := os.ReadFile(configpath)
	if err != nil {
		return fmt.Errorf("os.ReadFile: %w", err)
	}
	err = formatCueConfigBytes(&configBytes)
	if err != nil {
		return fmt.Errorf("formatting config: %w", err)
	}
	// Load in schema file
	schemaBytes, err := os.ReadFile(schemapath)
	if err != nil {
		return fmt.Errorf("os.ReadFile: %w", err)
	}
	err = formatSchemaBytes(&schemaBytes)
	if err != nil {
		return fmt.Errorf("formatting config: %w", err)
	}

	// Append bytes into a single array representing a new .cue file
	allBytes := append(schemaBytes[:], configBytes...)

	// Compile the bytes - consists of validation and default value evaluation
	ctx := cuecontext.New()
	val := ctx.CompileBytes(allBytes)
	if err := val.Err(); err != nil {
		return fmt.Errorf("cue.Context.CompileBytes: %w", err)
	}
	// Unmarshal data into config
	return val.Value().Decode(v)
}

func formatCueConfigBytes(cb *[]byte) error {
	for i, b := range *cb {
		if b == 35 {
			*cb = (*cb)[i:]
			break
		}
	}
	configString := strings.ReplaceAll(string(*cb), "conf.", "")
	*cb = []byte(configString)
	return nil
}

// formatSchemaBytes appends a byte for a newline character to the end of the schema bytes array
func formatSchemaBytes(sb *[]byte) error {
	*sb = append(*sb, []byte("\n")...)
	return nil
}

func run() error {
	configFile := flag.String(
		"configFile",
		"./infra/config/config.cue",
		"path to JSON configuration generated by CUE",
	)
	schemaFile := flag.String(
		"schemaFile",
		"./cue.mod/approval-service/schema.cue",
		"path to CUE schema to validate configFile against",
	)
	flag.Parse()

	var cfg ServerConfig
	if err := loadFromCue(*configFile, *schemaFile, &cfg); err != nil {
		return err
	}

	server, err := newServer(cfg)
	if err != nil {
		return err
	}

	if err := server.Serve(); err != nil {
		return fmt.Errorf("server error: %s", err)
	}

	return nil
}
